# Generated by Django 6.0 on 2025-12-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_options_alter_document_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
